export const GET_LOGGED_APPOINTMENT_REQUEST = 'GET_LOGGED_APPOINTMENT_REQUEST';
export const GET_LOGGED_APPOINTMENT_SUCCESS = 'GET_LOGGED_APPOINTMENT_SUCCESS';
export const GET_LOGGED_APPOINTMENT_FAIL = 'GET_LOGGED_APPOINTMENT_FAIL';

export const GET_PARTICULAR_SERVICE_EMPLOYEES_REQUEST = 'GET_PARTICULAR_SERVICE_EMPLOYEES_REQUEST';
export const GET_PARTICULAR_SERVICE_EMPLOYEES_SUCCESS = 'GET_PARTICULAR_SERVICE_EMPLOYEES_SUCCESS';
export const GET_PARTICULAR_SERVICE_EMPLOYEES_FAIL = 'GET_PARTICULAR_SERVICE_EMPLOYEES_FAIL';

export const BOOK_NEW_APPOINTMENT_REQUEST = 'BOOK_NEW_APPOINTMENT_REQUEST';
export const BOOK_NEW_APPOINTMENT_SUCCESS = 'BOOK_NEW_APPOINTMENT_SUCCESS';
export const BOOK_NEW_APPOINTMENT_FAIL = 'BOOK_NEW_APPOINTMENT_FAIL';
export const BOOK_NEW_APPOINTMENT_RESET = 'BOOK_NEW_APPOINTMENT_RESET';

export const UPDATE_EMPLOYEE_STATUS_REQUEST = 'UPDATE_EMPLOYEE_STATUS_REQUEST';
export const UPDATE_EMPLOYEE_STATUS_SUCCESS = 'UPDATE_EMPLOYEE_STATUS_SUCCESS';
export const UPDATE_EMPLOYEE_STATUS_FAIL = 'UPDATE_EMPLOYEE_STATUS_FAIL';
export const UPDATE_EMPLOYEE_STATUS_RESET = 'UPDATE_EMPLOYEE_STATUS_RESET';

export const GET_SERVICE_DURATION_REQUEST = 'GET_SERVICE_DURATION_REQUEST';
export const GET_SERVICE_DURATION_SUCCESS = 'GET_SERVICE_DURATION_SUCCESS';
export const GET_SERVICE_DURATION_FAIL = 'GET_SERVICE_DURATION_FAIL';

export const GET_SINGLE_BOOKING_REQUEST = 'GET_SINGLE_BOOKING_REQUEST';
export const GET_SINGLE_BOOKING_SUCCESS = 'GET_SINGLE_BOOKING_SUCCESS';
export const GET_SINGLE_BOOKING_FAIL = 'GET_SINGLE_BOOKING_FAIL';

// SLOT BOOKING
export const BOOK_NEW_SLOT_REQUEST = 'BOOK_NEW_SLOT_REQUEST';
export const BOOK_NEW_SLOT_SUCCESS = 'BOOK_NEW_SLOT_SUCCESS';
export const BOOK_NEW_SLOT_FAIL = 'BOOK_NEW_SLOT_FAIL';
export const BOOK_NEW_SLOT_RESET = 'BOOK_NEW_SLOT_RESET';

export const UPDATE_BOOKED_SLOT_REQUEST = 'UPDATE_BOOKED_SLOT_REQUEST';
export const UPDATE_BOOKED_SLOT_SUCCESS = 'UPDATE_BOOKED_SLOT_SUCCESS';
export const UPDATE_BOOKED_SLOT_FAIL = 'UPDATE_BOOKED_SLOT_FAIL';
export const UPDATE_BOOKED_SLOT_RESET = 'UPDATE_BOOKED_SLOT_RESET';

export const DELETE_SLOT_REQUEST = 'DELETE_SLOT_REQUEST';
export const DELETE_SLOT_SUCCESS = 'DELETE_SLOT_SUCCESS';
export const DELETE_SLOT_FAIL = 'DELETE_SLOT_FAIL';
export const DELETE_SLOT_RESET = 'DELETE_SLOT_RESET';

export const GET_SLOT_REQUEST = 'GET_SLOT_REQUEST';
export const GET_SLOT_SUCCESS = 'GET_SLOT_SUCCESS';
export const GET_SLOT_FAIL = 'GET_SLOT_FAIL';

export const GET_CUSTOMER_SLOT_REQUEST = 'GET_CUSTOMER_SLOT_REQUEST';
export const GET_CUSTOMER_SLOT_SUCCESS = 'GET_CUSTOMER_SLOT_SUCCESS';
export const GET_CUSTOMER_SLOT_FAIL = 'GET_CUSTOMER_SLOT_FAIL';


export const GET_SERVICENAME_REQUEST = 'GET_SERVICENAME_REQUEST';
export const GET_SERVICENAME_SUCCESS = 'GET_SERVICENAME_SUCCESS';
export const GET_SERVICENAME_FAIL = 'GET_SERVICENAME_FAIL';

export const GET_ACCURATE_SERVICE_DURATION_REQUEST = 'GET_ACCURATE_SERVICE_DURATION_REQUEST';
export const GET_ACCURATE_SERVICE_DURATION_SUCCESS = 'GET_ACCURATE_SERVICE_DURATION_SUCCESS';
export const GET_ACCURATE_SERVICE_DURATION_FAIL = 'GET_ACCURATE_SERVICE_DURATION_FAIL';

export const GET_CUSTOMER_BOOKING_NOTIFY_REQUEST = 'GET_CUSTOMER_BOOKING_NOTIFY_REQUEST';
export const GET_CUSTOMER_BOOKING_NOTIFY_SUCCESS = 'GET_CUSTOMER_BOOKING_NOTIFY_SUCCESS';
export const GET_CUSTOMER_BOOKING_NOTIFY_FAIL = 'GET_CUSTOMER_BOOKING_NOTIFY_FAIL';

export const UPDATE_MOBILENO_REQUEST = 'UPDATE_MOBILENO_REQUEST';
export const UPDATE_MOBILENO_SUCCESS = 'UPDATE_MOBILENO_SUCCESS';
export const UPDATE_MOBILENO_FAIL = 'UPDATE_MOBILENO_FAIL';
export const UPDATE_MOBILENO_RESET = 'UPDATE_MOBILENO_RESET';

export const GET_PARTNERS_BOOKING_REQUEST = 'GET_PARTNERS_BOOKING_REQUEST';
export const GET_PARTNERS_BOOKING_SUCCESS = 'GET_PARTNERS_BOOKING_SUCCESS';
export const GET_PARTNERS_BOOKING_FAIL = 'GET_PARTNERS_BOOKING_FAIL';

export const GET_PARTNERS_UNEMPLOYEED_BOOKING_REQUEST = 'GET_PARTNERS_UNEMPLOYEED_BOOKING_REQUEST';
export const GET_PARTNERS_UNEMPLOYEED_BOOKING_SUCCESS = 'GET_PARTNERS_UNEMPLOYEED_BOOKING_SUCCESS';
export const GET_PARTNERS_UNEMPLOYEED_BOOKING_FAIL = 'GET_PARTNERS_UNEMPLOYEED_BOOKING_FAIL';

export const GET_CUSTOMER_TODAY_BOOKING_REQUEST = 'GET_CUSTOMER_TODAY_BOOKING_REQUEST';
export const GET_CUSTOMER_TODAY_BOOKING_SUCCESS = 'GET_CUSTOMER_TODAY_BOOKING_SUCCESS';
export const GET_CUSTOMER_TODAY_BOOKING_FAIL = 'GET_CUSTOMER_TODAY_BOOKING_FAIL';

export const GET_CUSTOMER_IN_PARTNER_BOOKING_REQUEST = 'GET_CUSTOMER_IN_PARTNER_BOOKING_REQUEST';
export const GET_CUSTOMER_IN_PARTNER_BOOKING_SUCCESS = 'GET_CUSTOMER_IN_PARTNER_BOOKING_SUCCESS';
export const GET_CUSTOMER_IN_PARTNER_BOOKING_FAIL = 'GET_CUSTOMER_IN_PARTNER_BOOKING_FAIL';

export const GET_COMING_UP_BOOKINGS_REQUEST = 'GET_COMING_UP_BOOKINGS_REQUEST';
export const GET_COMING_UP_BOOKINGS_SUCCESS = 'GET_COMING_UP_BOOKINGS_SUCCESS';
export const GET_COMING_UP_BOOKINGS_FAIL = 'GET_COMING_UP_BOOKINGS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';