export const ADD_NEW_EMPLOYEE_REQUEST = 'ADD_NEW_EMPLOYEE_REQUEST';
export const ADD_NEW_EMPLOYEE_SUCCESS = 'ADD_NEW_EMPLOYEE_SUCCESS';
export const ADD_NEW_EMPLOYEE_FAIL = 'ADD_NEW_EMPLOYEE_FAIL';
export const ADD_NEW_EMPLOYEE_RESET = 'ADD_NEW_EMPLOYEE_RESET';

export const GET_LOGGED_EMPLOYEE_REQUEST = 'GET_LOGGED_EMPLOYEE_REQUEST';
export const GET_LOGGED_EMPLOYEE_SUCCESS = 'GET_LOGGED_EMPLOYEE_SUCCESS';
export const GET_LOGGED_EMPLOYEE_FAIL = 'GET_LOGGED_EMPLOYEE_FAIL';

export const GET_SINGLE_EMPLOYEE_REQUEST = 'GET_SINGLE_EMPLOYEE_REQUEST';
export const GET_SINGLE_EMPLOYEE_SUCCESS = 'GET_SINGLE_EMPLOYEE_SUCCESS';
export const GET_SINGLE_EMPLOYEE_FAIL = 'GET_SINGLE_EMPLOYEE_FAIL';

export const UPDATE_EMPLOYEE_REQUEST = 'UPDATE_EMPLOYEE_REQUEST';
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';
export const UPDATE_EMPLOYEE_FAIL = 'UPDATE_EMPLOYEE_FAIL';
export const UPDATE_EMPLOYEE_RESET = 'UPDATE_EMPLOYEE_RESET';

export const UPDATE_EMPLOYEE_SLOT_REQUEST = 'UPDATE_EMPLOYEE_SLOT_REQUEST';
export const UPDATE_EMPLOYEE_SLOT_SUCCESS = 'UPDATE_EMPLOYEE_SLOT_SUCCESS';
export const UPDATE_EMPLOYEE_SLOT_FAIL = 'UPDATE_EMPLOYEE_SLOT_FAIL';
export const UPDATE_EMPLOYEE_SLOT_RESET = 'UPDATE_EMPLOYEE_SLOT_RESET';

export const DELETE_EMPLOYEE_REQUEST = 'DELETE_EMPLOYEE_REQUEST';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_FAIL = 'DELETE_EMPLOYEE_FAIL';
export const DELETE_EMPLOYEE_RESET = 'DELETE_EMPLOYEE_RESET';

export const GET_ALL_EMPLOYEE_SERVICE_REQUEST = 'GET_ALL_EMPLOYEE_SERVICE_REQUEST'
export const GET_ALL_EMPLOYEE_SERVICE_SUCCESS = 'GET_ALL_EMPLOYEE_SERVICE_SUCCESS'
export const GET_ALL_EMPLOYEE_SERVICE_FAIL = 'GET_ALL_EMPLOYEE_SERVICE_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS';