export const ADD_NEW_SERVICES_REQUEST = 'ADD_NEW_SERVICES_REQUEST';
export const ADD_NEW_SERVICES_SUCCESS = 'ADD_NEW_SERVICES_SUCCESS';
export const ADD_NEW_SERVICES_FAIL = 'ADD_NEW_SERVICES_FAIL';
export const ADD_NEW_SERVICES_RESET = 'ADD_NEW_SERVICES_RESET';

export const GET_LOGGED_SERVICES_REQUEST = 'GET_LOGGED_SERVICES_REQUEST';
export const GET_LOGGED_SERVICES_SUCCESS = 'GET_LOGGED_SERVICES_SUCCESS';
export const GET_LOGGED_SERVICES_FAIL = 'GET_LOGGED_SERVICES_FAIL';

export const GET_SINGLE_SERVICE_REQUEST = 'GET_SINGLE_SERVICE_REQUEST';
export const GET_SINGLE_SERVICE_SUCCESS = 'GET_SINGLE_SERVICE_SUCCESS';
export const GET_SINGLE_SERVICE_FAIL = 'GET_SINGLE_SERVICE_FAIL';

export const UPDATE_SERVICE_REQUEST = 'UPDATE_SERVICE_REQUEST';
export const UPDATE_SERVICE_SUCCESS = 'UPDATE_SERVICE_SUCCESS';
export const UPDATE_SERVICE_FAIL = 'UPDATE_SERVICE_FAIL';
export const UPDATE_SERVICE_RESET = 'UPDATE_SERVICE_RESET';

export const GET_SERVICES_BY_SUBCATEGORY_REQUEST = 'GET_SERVICES_BY_SUBCATEGORY_REQUEST'
export const GET_SERVICES_BY_SUBCATEGORY_SUCCESS = 'GET_SERVICES_BY_SUBCATEGORY_SUCCESS'
export const GET_SERVICES_BY_SUBCATEGORY_FAIL = 'GET_SERVICES_BY_SUBCATEGORY_FAIL'

export const GET_SERVICESNAME_SUBCATE_REQUEST = 'GET_SERVICESNAME_SUBCATE_REQUEST'
export const GET_SERVICESNAME_SUBCATE_SUCCESS = 'GET_SERVICESNAME_SUBCATE_SUCCESS'
export const GET_SERVICESNAME_SUBCATE_FAIL = 'GET_SERVICESNAME_SUBCATE_FAIL'

export const GET_SERVICESNAME_DURATIONS_REQUEST = 'GET_SERVICESNAME_DURATIONS_REQUEST'
export const GET_SERVICESNAME_DURATIONS_SUCCESS = 'GET_SERVICESNAME_DURATIONS_SUCCESS'
export const GET_SERVICESNAME_DURATIONS_FAIL = 'GET_SERVICESNAME_DURATIONS_FAIL'

export const UPDATE_SALOON_IMAGES_REQUEST = "UPDATE_SALOON_IMAGES_REQUEST"
export const UPDATE_SALOON_IMAGES_SUCCESS = "UPDATE_SALOON_IMAGES_SUCCESS"
export const UPDATE_SALOON_IMAGES_FAIL = "UPDATE_SALOON_IMAGES_FAIL"
export const UPDATE_SALOON_IMAGES_RESET = "UPDATE_SALOON_IMAGES_RESET"

export const UPDATE_SALOON_DESCRIPTION_REQUEST = "UPDATE_SALOON_DESCRIPTION_REQUEST"
export const UPDATE_SALOON_DESCRIPTION_SUCCESS = "UPDATE_SALOON_DESCRIPTION_SUCCESS"
export const UPDATE_SALOON_DESCRIPTION_FAIL = "UPDATE_SALOON_DESCRIPTION_FAIL"
export const UPDATE_SALOON_DESCRIPTION_RESET = "UPDATE_SALOON_DESCRIPTION_RESET"

export const GET_LOGGED_SALOON_REQUEST = 'GET_LOGGED_SALOON_REQUEST';
export const GET_LOGGED_SALOON_SUCCESS = 'GET_LOGGED_SALOON_SUCCESS';
export const GET_LOGGED_SALOON_FAIL = 'GET_LOGGED_SALOON_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';