export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL';

export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL';
export const PROFILE_UPDATE_RESET = 'PROFILE_UPDATE_RESET';

export const PASSWORD_UPDATE_REQUEST = "PASSWORD_UPDATE_REQUEST";
export const PASSWORD_UPDATE_SUCCESS = "PASSWORD_UPDATE_SUCCESS";
export const PASSWORD_UPDATE_FAIL = "PASSWORD_UPDATE_FAIL";
export const PASSWORD_UPDATE_RESET = "PASSWORD_UPDATE_RESET";

// NEW SALOON CREATION
export const CREATE_NEW_SALOON_REQUEST = 'CREATE_NEW_SALOON_REQUEST';
export const CREATE_NEW_SALOON_SUCCESS = 'CREATE_NEW_SALOON_SUCCESS';
export const CREATE_NEW_SALOON_FAIL = 'CREATE_NEW_SALOON_FAIL';

export const REGISTER_PARTNERS_BOOKING_REQUEST = 'REGISTER_PARTNERS_BOOKING_REQUEST';
export const REGISTER_PARTNERS_BOOKING_SUCCESS = 'REGISTER_PARTNERS_BOOKING_SUCCESS';
export const REGISTER_PARTNERS_BOOKING_FAIL = 'REGISTER_PARTNERS_BOOKING_FAIL';
export const REGISTER_PARTNERS_BOOKING_RESET = 'REGISTER_PARTNERS_BOOKING_RESET';


export const GET_SALOON_NAME_INDIVIDUAL_REQUEST = 'GET_SALOON_NAME_INDIVIDUAL_REQUEST';
export const GET_SALOON_NAME_INDIVIDUAL_SUCCESS = 'GET_SALOON_NAME_INDIVIDUAL_SUCCESS';
export const GET_SALOON_NAME_INDIVIDUAL_FAIL = 'GET_SALOON_NAME_INDIVIDUAL_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';